### ISSUE TITLE
java.lang.IllegalStateException: Cannot get a text value from a numeric cell

### ISSUE THREAD

**Issue by dlebrero** [akvo/akvo-flow-services#223]
https://sentry.io/akvo-foundation/flow-services/issues/612532827/

```
java.lang.IllegalStateException: Cannot get a text value from a numeric cell
  File "XSSFCell.java", line 845, in org.apache.poi.xssf.usermodel/typeMismatch
  File "XSSFCell.java", line 294, in org.apache.poi.xssf.usermodel/getRichStringCellValue
  File "XSSFCell.java", line 246, in org.apache.poi.xssf.usermodel/getStringCellValue
  ?, in sun.reflect/invoke
  File "DelegatingMethodAccessorImpl.java", line 43, in sun.reflect/invoke
...
(37 additional frame(s) were not displayed)

Job (DEFAULT.6E7A8201-687C-4A31-9AA6-3C5764D869E2 threw an exception.
```

**Comment by stellanl** [comment]
This one is really hard to track down without those 37 additional stack frames...
I have found 4 instances of this error as Info-level log lines in the live server, but not even a hint about which survey/URL it was processing or anything.

**Comment by dlebrero** [comment]
Added some additional logging at https://github.com/akvo/akvo-flow-services/issues/224

**Comment by stellanl** [comment]
The longer stacktrace (in Sentry) looks like this:
XSSFCell.java in org.apache.poi.xssf.usermodel/typeMismatch at line 845
XSSFCell.java in org.apache.poi.xssf.usermodel/getRichStringCellValue at line 294
XSSFCell.java in org.apache.poi.xssf.usermodel/getStringCellValue at line 246
sun.reflect/invoke
DelegatingMethodAccessorImpl.java in sun.reflect/invoke at line 43
Method.java in java.lang.reflect/invoke at line 498
Reflector.java in clojure.lang/invokeMatchingMethod at line 93
Reflector.java in clojure.lang/invokeNoArgInstanceMember at line 313
uploader.clj in akvo.flow-services.uploader/[fn] at line 127

Nothing I can do, since I don't know Clojure.

**Comment by dlebrero** [comment]
@stellanl happy to help but I would need to know what flow-services is supposed to do

**Comment by stellanl** [comment]
AFAIK, it's supposed to
1. Check that the question numbers in the column headers all match questions in the survey(form)
This has recently gotten more complicated since the repeatable groups moved to separate sheets. Sheets named "Group n" should be checked as well as the sheet named "Raw data". The relevant column headers have moved down from the first row to the second. For a column titled "nnn|foo" there may now also be one titled "nnn|foo--OTHER--" 
2. Call the verify() method which checks repeat counts etc.
3. Call the executeImport() method.
