### ISSUE TITLE
Unhook Flow Service from Sentry

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-services#281]
- we do not react to the errors right now 
- too many coming in causing higher costs 
- do not have the space to do a clean up (need to finish assignments first) 

--> Turn off Sentry and we will keep the Google updates in case we need to understand errors for the time being and later we can plug Sentry back in and do proper filtering and reacting to the issues.

**Comment by muloem** [comment]
After looking into the Sentry stats, it turns out that Flow services is not the highest consumer of event quota but rather the flow app (over 70% of event quota).  So we will leave Flow services connected and instead migrate the app to a different logging service (firebase/crashlytics) https://github.com/akvo/akvo-flow-mobile/issues/1531 

Till then we also limit the number of events that are actually sent to Sentry https://github.com/akvo/akvo-flow-mobile/issues/1545
